import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { CartProvider } from "../components/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <CartProvider>
          <nav className="w-full flex justify-between items-center px-6 py-4 bg-zinc-950/80 border-b border-zinc-800 mb-8">
            <Link href="/" className="text-xl font-bold text-white">Eco Retail</Link>
            <div className="flex gap-4">
              <Link href="/marketplace">
                <button className="px-4 py-2 rounded bg-green-600 text-white hover:bg-green-700 transition shadow">Marketplace</button>
              </Link>
            </div>
          </nav>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
