import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { CartProvider } from "../components/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-zinc-900`}>
        <CartProvider>
          {/* Walmart-style header */}
          <header className="w-full bg-blue-700 text-white flex flex-col">
            <div className="flex items-center justify-between px-6 py-3">
              <Link href="/" className="flex items-center gap-2 text-2xl font-bold">
                <span className="bg-white text-blue-700 rounded-full px-2 py-1 font-black">E</span>co Retail
              </Link>
              <div className="flex-1 mx-8">
                <input type="text" placeholder="Search everything at Eco Retail..." className="w-full px-4 py-2 rounded-full text-white" />
              </div>
              <div className="flex gap-6 items-center">
                <Link href="/marketplace" className="hover:underline">Marketplace</Link>
                <Link href="/checkout" className="hover:underline">Cart</Link>
                <Link href="#" className="hover:underline">Account</Link>
              </div>
            </div>
          </header>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
